# This workflow installs dependencies, builds the project, and restarts the PM2 process on the EC2 server.
name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 1. Install dependencies for the whole project
    - name: Install Dependencies
      run: npm install

    # 2. Navigate to backend and install/build (if necessary)
    - name: Backend Setup
      run: |
        cd backend
        npm install

    # 3. Restart the application using PM2
    - name: Restart PM2 Server
      run: |
        cd backend
        sudo pm2 restart server || sudo pm2 start server.js --name "server"
